#!/bin/sh

chords_path=$DOCUMENT_ROOT/items/chords/items

ids="`qhash -r -g "Entrada" -g "Aleluia" -g "Ofertório" -g "Santo" -g "Comunhão" -g "Ação de Graças" -g "Saída" $chords_path/types.db`"
ids="`echo $ids | sed 's/ / -R/g'`"
rands="`qhash -m1 -R$ids $chords_path/assoc.db`"
echo $rands | sed 's/ /:0 /g' | tr ' ' '\n' > $ITEM_PATH/data.txt
