#!/bin/sh

chords_path=$DOCUMENT_ROOT/items/chords/items

qhash -m1 -ra $chords_path/types.db \
	-R"Entrada" -R"Aleluia" -R"Ofertório" -R"Santo" \
	-R"Comunhão" -R"Ação de Graças" -R"Saída" \
	$chords_path/assoc.db | while read format id
do
	echo $id:0:$format
done > $ITEM_PATH/data.txt
