#!/bin/sh

im $OWNER || Forbidden

if test $REQUEST_METHOD = POST; then
	c=0
	while test $c -lt $HTTP_PARAM_count; do
		eval "csong=\${HTTP_PARAM_song_$c}"
		eval "ct=\${HTTP_PARAM_t_$c}"
		csong="`urldecode "$csong"`"
		echo $csong:$ct
		c=`math $c + 1`
	done > $ITEM_PATH/data.txt

	SeeOther .
fi

chords_path="$DOCUMENT_ROOT/items/chords/items"
choir_path="$DOCUMENT_ROOT/items/choir/items/`cat $ITEM_PATH/choir`"

proc() {
	counter=0
	while IFS=: read song t fmt; do
		formatstr="`qhash -a $chords_path/types.db -g$counter $choir_path/format.db | cut -d ' ' -f1-`"
		formatid="`echo $formatstr | awk '{ print $2 }'`"
		format="`echo $formatstr | cut -d ' ' -f3-`"
		path="$chords_path/$song"
		echo "<div class='f h'>"
		echo "<select name='song_$counter'>"
		qhash -m1 -q $chords_path/links.db -rg"$formatid" $chords_path/assoc.db | \
			while read typeid id title; do
			attr="`test "$song" != "$title" || echo selected`"
			echo "<option $attr value='$title'>$title</option>"
		done
		echo "</select>"
		echo "<input name='t_$counter' type='number' step='1' value='$t'></input>"
		RB 👁 "/chords/$song?t=$t"
		echo "</div>"
		counter="`math $counter + 1`"
	done
	echo "<input type='hidden' name='count' value='$counter'></input>"
}

echo "<form action='.' method='POST' class='v f fic'>"
cat $ITEM_PATH/data.txt | proc
echo "<button class='rs ps'>`_ Submit`</button>"
echo "</form>"
