#!/bin/sh

choirs_path="$DOCUMENT_ROOT/items/choir/items/"
choir="`cat choir`"
choir_path="$choirs_path/$choir"
choir_title="`cat $choir_path/title`"
choir="`echo $choir_title | translate`"

im $OWNER $choir || Forbidden

if test $REQUEST_METHOD = POST; then
	c=0
	cp data.txt /tmp/data.txt
	test ! -z "$HTTP_PARAM_amount" || \
		HTTP_PARAM_amount="`wc -l data.txt | awk '{print $1}'`"

	test "$HTTP_PARAM_amount" -ge "1" || Fatal 400 "What happened? Don't submit such a short one."

	while test "$c" -lt "$HTTP_PARAM_amount"; do
		eval "csong=\"\${HTTP_PARAM_song_$c}\""
		eval "ct=\"\${HTTP_PARAM_t_$c}\""
		eval "cfmt=\"\${HTTP_PARAM_fmt_$c}\""
		csong="`test -z "$csong" || urldecode "$csong"`"
		cfmt="`test -z "$cfmt" || urldecode "$cfmt"`"
		echo $csong:$ct:$cfmt
		c="`math $c + 1`"
	done > data.txt

	SeeOther .
fi

chords_path="$DOCUMENT_ROOT/items/chords/items"
choir_path="$DOCUMENT_ROOT/items/choir/items/`cat choir`"

. $chords_path/../lib

tmp=$DOCUMENT_ROOT/tmp/$rid

song_options() {
	if test "$fmt" = "any"; then
		$qdb -l $chords_path/index.db
	else
		cmd="$qdb -kr `$qdb -rg"$fmt" $chords_path/assoc.db | sed 's/\</-g/g'` $chords_path/index.db"
		$cmd
	fi | while read link flags title; do
		test ! -z "$title" || continue
		printf '<option value="%s">%s</option>\n' "$link" "$title"
	done | tee $tmp$fmt
}

format_options() {
	echo "<option value='any'>`_ Any`</option>"
	$qdb -l $chords_path/types.db | \
		while read link format; do
			echo "<option value='$link'>$format</option>"
		done
}

proc() {
	counter=0
	while IFS=: read song t fmt; do
		echo "<div class='f h fic'><label class='v0 f'>"

		echo "<select name='fmt_$counter' data-value='$fmt'>"
		if test -e $tmp"fmt"; then
			cat $tmp"fmt"
		else
			format_options | tee $tmp"fmt"
		fi
		echo "</select>"

		echo "<select name='song_$counter' data-value='$song'>"

		if test -e $tmp"$fmt"; then
			cat $tmp"$fmt"
		else
			song_options
		fi

		echo "</select></label>"
		test ! -z "$t" || t=0
		flags=""
		echo key_select $chords_path$song/data.txt "$t" "t_$counter" 1 >&2
		key_select $chords_path$song/data.txt "$t" "t_$counter" 1
		echo "</div>"
		counter="`math $counter + 1`"
	done
	cat <<!
<label class='h f fic'>
<span>`_ Amount`</span>
<input type='number' step='1' name='amount' value='$counter'></input>
</label>
!
}

cat <<!
<form action='.' method='POST' class='v f fic'>
`cat data.txt | proc`
<button class='rs ps'>`_ Submit`</button>
</form>
<script>
let val = parseInt(document.querySelector('input[name="amount"]').value, 10);

function auto_select(select) {
  const target = select.dataset.value;

  for (let opt of select.options) {
    if (opt.value === target) {
      opt.selected = true;
    } else {
      opt.selected = false;
    }
  }
}

document.querySelectorAll('select[data-value]').forEach(auto_select);

</script>
!
