#!/bin/sh

flags=""
test -z "$HTTP_PARAM_b" || flags="$flags -b"
test -z "$HTTP_PARAM_l" || flags="$flags -l"
if test ! -z "$HTTP_PARAM_s"; then
	nc=1
	flags="$flags -C"
fi

index() {
	local counter=0
	while IFS=: read song t; do
		path="$DOCUMENT_ROOT/items/chords/items/$song/data.txt"
		echo "<div><a href='#$counter'>`cat "$path" | head -n 1`</a></div>"
		counter="`math $counter + 1`"
	done
}

TypeBtn() {
	if test ! -z "$HTTP_PARAM_s"; then
		RB "🎸" "?"
	else
		RB "👄" "?s=1"
		test -z "$HTTP_PARAM_l" \
			&& RB "🏛️" "?l=1" \
			|| RB "🔠" "?"
	fi
}

cat >> $DOCUMENT_ROOT/tmp/fun <<!
<label id="index" class="$RBS menu">
	≡
	<input type="checkbox" />
	<div class="abs v ar8 p c0 ts btn ttc">`cat $ITEM_PATH/data.txt | index`</div>
</label>
`EditBtn`
`TypeBtn`
!

TForm() {
	cat <<!
<form action='.#$1' method='POST' class='h f fic'>
<input name='t' type='number' step='1' value='$2'></input>
<input name='n' type='hidden' value='$1'></input>
<input name='l' type='hidden' value='$HTTP_PARAM_l'></input>
<input name='s' type='hidden' value='$HTTP_PARAM_s'></input>
<button>✔</button>
</form>
!
}

if im $OWNER && test -z "$nc"; then
	shift_chords() {
		# add ⟳
		echo "<span class='f h fic'>`TForm $1 $2`</span>"
	}
else
	shift_chords() {
	}
fi

show() {
	counter=0
	while IFS=: read song t; do
		song_dir="$DOCUMENT_ROOT/items/chords/items/$song"
		path="$song_dir/data.txt"
		lypath="$song_dir/data.ly"
		test -f "$lypath" &&
			lyink="<a href='/chords/$song/data.ly'>𝄞</a> " ||
			lyink=

		test -f "$song_dir/type" \
			&& type="<h6>`cat $song_dir/type | head -n 1`</h6>" \
			|| type=""

		cat - <<!
<span id='$counter' class='h f fic fcsb mt32'>
<div class="v0 f">
<h2 class='tac'>$lyink`cat "$path" | head -n 1`</h2>
$type
</div>
`shift_chords $counter $t`
</span>
!
		cat "$path" | tail -n +3 | transp -h $flags -t $t
		counter="`math $counter + 1`"
	done
}

if test ! -z "$HTTP_PARAM_n"; then
	count="`wc -l $ITEM_PATH/data.txt`"
	cn=0
	cp $ITEM_PATH/data.txt $ITEM_PATH/backup.txt
	cat $ITEM_PATH/data.txt | while IFS=: read song ct; do
		test $cn -eq $HTTP_PARAM_n \
			&& echo $song:$HTTP_PARAM_t || echo $song:$ct
		cn=`math $cn + 1`
	done > $ITEM_PATH/data.txt

	SeeOther "/sb/$iid/?s=$HTTP_PARAM_s&l=$HTTP_PARAM_l"
fi

echo "<pre lang='pt' class='v0 chords'>"
cat $ITEM_PATH/data.txt | show
echo "</pre>"
